apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: coolstore-eap74
  labels:
    app: coolstore
    component: application
    version: eap74
spec:
  lookupPolicy:
    local: false
