apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: coolstore
    component: database
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgresql
  selector:
    app: coolstore
    component: database
