apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data
  labels:
    app: coolstore
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
